Chore/set up the app mobile architecture
XPEHO/YAKI pull request #24
Opened 2023-02-16 16:25 UTC by MaximeHavez

# Description
What are changes related to ?

# Linked Issues
What are the issues fixed by this pull request ?

# Changes
What does it change ?
Is is a breaking change ?
Is is a new feature ?
Is is a patch, fix, hotfix ?

# Screenshots
Put screenshots (if any)

# Tests
How has it been tested ?

- [ ] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
Precise any other information

2023-02-16 16:46 UTC, PiotrFLEURY requested changes
Please fix pubspec.yaml

2023-02-16 16:46 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +  flutter_hooks: ^0.18.0
Remove

2023-02-16 16:46 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +  hooks_riverpod: ^2.2.0
Remove

2023-02-16 16:46 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +
Add flutter_riverpod see [https://pub.dev/packages/flutter_riverpod/install](https://pub.dev/packages/flutter_riverpod/install)

2023-02-16 16:46 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +  flutter:
sort dependencies

2023-02-16 16:46 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +  json_serializable: ^6.6.1
Remove

2023-02-17 08:30 UTC, PiotrFLEURY requested changes
The create base folders for Flutter front architecture pattern are missing. Please check issue

2023-02-17 08:30 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +description: A new Flutter project.
set a clear description of the app

2023-02-17 08:30 UTC, PiotrFLEURY commented on yaki_mobile/pubspec.yaml
> +dependencies:
some dependencies are still missing. Please read the linked Google doc in the issue.

2023-02-17 10:42 UTC, PiotrFLEURY approved these changes

2023-02-17 10:50 UTC, FlorianFlouquet approved these changes

2023-02-17 10:54 UTC, merged