Feat/declaration back
XPEHO/YAKI pull request #34
Opened 2023-02-23 16:02 UTC by HaddoucheRym

# Description

What are changes related to ?
Teammate Working Mode Declaration Feat

# Linked Issues
#4

What are the issues fixed by this pull request ?

# Changes
What does it change ?
Is is a breaking change ? no
Is is a new feature ? yes
Is is a patch, fix, hotfix ? no

# Screenshots
Put screenshots (if any) N/A

# Tests
How has it been tested ?

- [x] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
Precise any other information

2023-02-23 16:24 UTC, FlorianFlouquet requested changes

2023-02-23 16:24 UTC, FlorianFlouquet commented on yaki_backend/src/repository.ts
>  interface Captain {
Is that file still necessary ?

2023-02-23 16:30 UTC, HaddoucheRym reviewed
resolved conversation

2023-02-23 16:32 UTC, FlorianFlouquet approved these changes

2023-02-24 08:14 UTC, LaurentMag approved these changes

2023-02-24 08:17 UTC, MaximeHavez approved these changes

2023-02-24 08:19 UTC, merged