Feat/authentication front
XPEHO/YAKI pull request #40
Opened 2023-02-28 14:50 UTC by MaximeHavez

# Description
logging with back

# Linked Issues
Authentication

# Changes
Possible to log by the app

# Screenshots
N/A

# Tests
How has it been tested ?

- [x] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
Precise any other information

2023-02-28 15:04 UTC, PiotrFLEURY requested changes

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/Authentification.dart
> +import '../shared/views/Header.dart';
use import packages

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/Authentification.dart
> +  bool isChecked = false;
this boolean should not exist in a consumer widget

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/Authentification.dart
> +                              // });
remove commented code

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/Authentification.dart
> +    final providerlogin = ref.watch(loginProvider);
```suggestion
    final providerlogin = ref.read(loginProvider);
```

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/logged.dart
> +class logged extends StatelessWidget {
Naming
```suggestion
class Logger extends StatelessWidget {
```

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/shared/views/ButtonApp.dart
>  import '../../../styles/HeaderTextStyle.dart';
import packages

2023-02-28 15:04 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/shared/views/InputApp.dart
> +      },
??

2023-03-01 08:57 UTC, FlorianFlouquet approved these changes

2023-03-01 13:36 UTC, FlorianFlouquet approved these changes

2023-03-01 13:38 UTC, LaurentMag approved these changes

2023-03-01 13:43 UTC, PiotrFLEURY requested changes

2023-03-01 13:43 UTC, PiotrFLEURY commented on yaki_mobile/config.json
> +}
remove from git

2023-03-01 13:45 UTC, PiotrFLEURY approved these changes

2023-03-01 13:46 UTC, HaddoucheRym approved these changes

2023-03-01 14:43 UTC, merged