fix(declaration): fixed bug
XPEHO/YAKI pull request #65
Opened 2023-03-08 10:41 UTC by HaddoucheRym

# Description
What are changes related to ?
fixed declaration bug

# Linked Issues
What are the issues fixed by this pull request ?
#63 

# Changes
What does it change ?
Is is a breaking change ?No
Is is a new feature ?No
Is is a patch, fix, hotfix ?Yes

# Screenshots
Put screenshots (if any) N/A

# Tests
How has it been tested ?

- [X] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
Precise any other information

2023-03-08 14:11 UTC, FlorianFlouquet approved these changes

2023-03-08 14:12 UTC, PiotrFLEURY requested changes

2023-03-08 14:12 UTC, PiotrFLEURY commented on yaki_backend/src/features/declaration/declaration.service.ts
> +      return "One or more mandatory information is missing."
should be an error no ? the front should receive a 400 BAD REQUEST in this case

2023-03-08 15:05 UTC, HaddoucheRym commented on yaki_backend/src/features/declaration/declaration.service.ts
> +      return "You have to declare a teamMateID"
I prefer not to use an exception because it is a less serious error, caused by missing data that can be handled by the application.

2023-03-08 15:33 UTC, PiotrFLEURY requested changes

2023-03-08 15:33 UTC, PiotrFLEURY commented on yaki_backend/src/features/declaration/declaration.service.ts
> +      return "One or more mandatory information is missing."
not a 500, it should be a 400 because the problem comes from the request

2023-03-09 12:31 UTC, LaurentMag submitted a review, later dismissed

2023-03-09 12:54 UTC, MaximeHavez submitted a review, later dismissed

2023-03-09 12:56 UTC, FlorianFlouquet approved these changes

2023-03-09 16:52 UTC, PiotrFLEURY approved these changes

2023-03-10 09:10 UTC, MaximeHavez approved these changes

2023-03-10 09:11 UTC, LaurentMag approved these changes

2023-03-10 09:22 UTC, merged