chore(create-ci): setup CI for testing and building
XPEHO/YAKI pull request #66
Opened 2023-03-08 13:15 UTC by FlorianFlouquet

# Description
Creation of a file to automate build and test process

# Linked Issues
#17 

# Changes
CI got harsher

# Screenshots
N/A

# Tests
How has it been tested ?

- [x] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
N/A

2023-03-08 13:26 UTC, PiotrFLEURY approved these changes
Just a comment about flutter version, rest is OK

2023-03-08 13:26 UTC, PiotrFLEURY commented on .github/workflows/test_&_build.yaml
> +          flutter-version: '3.7.3'
latest version is 3.7.6

2023-03-08 13:42 UTC, HaddoucheRym approved these changes

2023-03-09 12:44 UTC, PiotrFLEURY requested changes

2023-03-09 12:44 UTC, PiotrFLEURY commented on .github/workflows/test_&_build.yaml
> +           flutter-version: '3.7.3'
```suggestion
           flutter-version: '3.7.6'
```

2023-03-09 12:44 UTC, PiotrFLEURY commented on yaki_backend/src/__test__/server.test.ts
>  test("it should pass", async () => {
delete this useless test

2023-03-09 12:44 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/authentication/authentication.dart
> +    ref.watch(loginProvider);
useless, remove it

2023-03-09 12:44 UTC, PiotrFLEURY commented on yaki_mobile/test/widget_test.dart
> +// import 'package:flutter/material.dart';
remove useless test

2023-03-09 12:45 UTC, MaximeHavez submitted a review, later dismissed

2023-03-10 11:11 UTC, PiotrFLEURY approved these changes

2023-03-10 11:54 UTC, LaurentMag approved these changes

2023-03-10 13:33 UTC, merged