Feature/captain mobile view
XPEHO/YAKI pull request #71
Opened 2023-03-10 15:34 UTC by MaximeHavez

# Description
What are changes related to ?

# Linked Issues
What are the issues fixed by this pull request ?

# Changes
What does it change ?
Is is a breaking change ?
Is is a new feature ?
Is is a patch, fix, hotfix ?

# Screenshots
Put screenshots (if any)

# Tests
How has it been tested ?

- [ ] Manually
- [ ] Automated tests
- [ ] QA
- [ ] Other

# Additional information
Precise any other information

2023-03-13 12:39 UTC, PiotrFLEURY requested changes

2023-03-13 12:39 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
> +                status: 'Remote',
hard coded text, please translate

2023-03-13 12:39 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
> +                          '16/10/2022 09h40',
hard coded value, should be dynamic

2023-03-13 12:39 UTC, PiotrFLEURY commented on yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
> +                          'Remote',
hard coded text, please translate

2023-03-15 09:48 UTC, PiotrFLEURY approved these changes

2023-03-15 09:51 UTC, PiotrFLEURY approved these changes

2023-03-15 09:57 UTC, HaddoucheRym approved these changes

2023-03-15 09:58 UTC, merged